name: CI Gradle + Containerfile (podman)

on:
  push:
    branches: ["main"]

jobs:
  build-gradle:
    name: Build WAR with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build WAR with Gradle
        run: gradle clean war

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-war
          path: build/libs/*.war

  build-containerfile:
    name: Build Image with Podman
    runs-on: ubuntu-latest
    needs: build-gradle

    # Required to be able to push to GHCR using GITHUB_TOKEN
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-war
          path: build/libs

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Podman login to GHCR
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GHCR_TOKEN" | \
          podman login ghcr.io \
            --username "$GHCR_USERNAME" \
            --password-stdin

      - name: Set image tags
        run: |
          echo "IMAGE_REGISTRY=ghcr.io" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build image from Containerfile
        run: |
          podman build \
            -f Containerfile \
            -t $IMAGE_NAME:$IMAGE_TAG_SHA \
            -t $IMAGE_NAME:latest \
            .

      - name: Push image
        run: |
          podman push $IMAGE_NAME:$IMAGE_TAG_SHA
          podman push $IMAGE_NAME:latest
